apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: balazshasprai
    repository: jx3-test
  - key: staging
  - key: production
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-issuer
      kubernetes.io/ingress.class: external
    domain: bhas.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: true
      production: true
  pipelineUser:
    username: balazshasprai
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
